name: Run Tests and Code Checks

# События, которые запускают workflow
on:
  push:
    branches:
      - master
      - release
  pull_request:
    branches:
      - master
      - release
      - develop

jobs:
  build:
    runs-on: ubuntu-latest
    env: 
      FULL_NAME: "Мисенко Андрей Александрович"
      GROUP_NUMBER: "M3115"

    steps:
    # 1. Клонируем репозиторий
    - name: Checkout repository
      uses: actions/checkout@v3

    # 2. Выводим ФИО, номер группы и ник GitHub
    - name: Display user information
      run: |
        echo "Full Name: ${{ env.FULL_NAME }}"
        echo "Group: ${{ env.GROUP_NUMBER }}"
        echo "GitHub Username: ${{ github.actor }}"

    # 3. Устанавливаем Python 3.13
    - name: Set up Python 3.13
      uses: actions/setup-python@v4
      with:
        python-version: 3.13

    # 4. Устанавливаем зависимости
    - name: Install dependencies
      run: |
        pip install flake8

    # 5. Запускаем юнит-тесты
    - name: Run unit tests
      run: |
        python -m unittest discover -s geometric_lib/tests

    # 6. Проверяем стиль кода
    - name: Lint code with flake8
      run: |
        flake8 . --max-line-length=79
