name: Run Tests and Code Checks

on:
  push:
    branches:
      - main
      - release
  pull_request:
    branches:
      - master
      - release
      - develop

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    # Показать текущую директорию
    - name: Show current directory
      run: pwd

    - name: Set up Python 3.13
      uses: actions/setup-python@v4
      with:
        python-version: 3.13

    - name: Install dependencies
      run: |
        pip install flake8

    - name: Run unit tests
      run: |
        python -m unittest discover -s geometric_lib/tests

    - name: Lint code with flake8
      run: |
        flake8 . --max-line-length=79
